In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Read the dataset
# The file is assumed to be in the same directory as this script
data = pd.read_csv('opportunity_preprocessed.csv')
data.head()

,timestamp,accX,accY,accZ,gyroX,gyroY,gyroZ,magneticX,magneticY,magneticZ,activity,user_id
0,0,-920.0,-358.0,171.0,-145.0,47.0,48.0,389.0,202.0,593.0,0,1
1,33,-942.0,-357.0,161.0,-318.0,-6.0,23.0,390.0,196.0,597.0,0,1
2,67,-928.0,-357.0,143.0,-426.0,13.0,49.0,392.0,192.0,598.0,0,1
3,100,-897.0,-377.0,142.0,-348.0,46.0,54.0,390.0,187.0,601.0,0,1
4,133,-877.0,-398.0,153.0,-329.0,76.0,100.0,389.0,179.0,605.0,0,1

In [3]:
# Convert the timestamp to datetime if necessary (it might be in nanoseconds)
data['timestamp'] = pd.to_datetime(data['timestamp'], unit='ms')
data.head()

,timestamp,accX,accY,accZ,gyroX,gyroY,gyroZ,magneticX,magneticY,magneticZ,activity,user_id
0,1970-01-01 00:00:00.000,-920.0,-358.0,171.0,-145.0,47.0,48.0,389.0,202.0,593.0,0,1
1,1970-01-01 00:00:00.033,-942.0,-357.0,161.0,-318.0,-6.0,23.0,390.0,196.0,597.0,0,1
2,1970-01-01 00:00:00.067,-928.0,-357.0,143.0,-426.0,13.0,49.0,392.0,192.0,598.0,0,1
3,1970-01-01 00:00:00.100,-897.0,-377.0,142.0,-348.0,46.0,54.0,390.0,187.0,601.0,0,1
4,1970-01-01 00:00:00.133,-877.0,-398.0,153.0,-329.0,76.0,100.0,389.0,179.0,605.0,0,1

In [4]:
cols = ['accX',	'accY',	'accZ',	
        'gyroX', 'gyroY', 'gyroZ',	
        'magneticX', 'magneticY', 'magneticZ']
print("Descriptive Statistics:")
data[cols].describe()

Descriptive Statistics:

,accX,accY,accZ,gyroX,gyroY,gyroZ,magneticX,magneticY,magneticZ
count,854324.000000,854324.00000,854324.000000,854324.00000,854324.000000,854324.000000,854324.000000,854324.000000,854324.000000
mean,-596.718467,-527.82981,-10.373651,-86.15918,4.316273,37.600403,271.678580,184.563558,-5.011802
std,527.591042,289.50250,307.706465,859.68743,721.501741,822.036621,570.407139,419.980414,440.910909
min,-5643.000000,-5927.00000,-5111.000000,-25946.00000,-11983.000000,-11906.000000,-3367.000000,-2001.000000,-1537.000000
25%,-939.000000,-744.00000,-148.000000,-346.00000,-198.000000,-167.000000,-176.000000,-138.000000,-400.000000
50%,-822.000000,-479.00000,21.000000,-68.00000,21.000000,41.000000,358.000000,213.000000,26.000000
75%,-376.000000,-336.00000,167.000000,173.00000,216.000000,240.000000,710.000000,527.000000,379.000000
max,4787.000000,3436.00000,4629.000000,11265.00000,9964.000000,11854.000000,2195.000000,2207.000000,2133.000000

In [5]:
# Class Distribution
print("\nClass Distribution:")
class_counts = data['activity'].value_counts()
total_counts = class_counts.sum()
class_percentages = (class_counts / total_counts) * 100
print(class_counts)
print(class_percentages)

Class Distribution:
activity
1    345397
2    199213
0    162530
4    136852
5     25395
Name: count, dtype: int64
activity
1    39.728797
2    22.914191
0    18.694781
4    15.741206
5     2.921024
Name: count, dtype: float64

In [6]:
# Time Interval Analysis
data['time_diff'] = data['timestamp'].diff().dt.total_seconds()
print("\nTime Intervals (seconds):")
data['time_diff'].describe()

Time Intervals (seconds):

count    869386.000000
mean          0.001743
std           6.450030
min       -2364.210000
25%           0.033000
50%           0.033000
75%           0.034000
max           0.034000
Name: time_diff, dtype: float64

In [ ]:
# Correlation Analysis
correlation_matrix = data[cols].corr().round(2)
print("\nCorrelation Matrix:")
correlation_matrix

In [ ]:
# Outlier Detection using Z-Score
z_scores = np.abs((data[cols] - data[cols].mean()) / data[cols].std())
outliers = (z_scores > 3).any(axis=1)
print("\nNumber of outliers detected:", outliers.sum())

In [ ]:
# Plot the class distribution
plt.figure(figsize=(10, 6))
sns.barplot(x=class_counts.index, y=class_percentages, palette='viridis')
plt.title('Distribution of Activities')
plt.xlabel('Activity')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
# Histogram of Sampling Frequency
data['time_diff'].plot(kind='hist', bins=50, title='Histogram of Sampling Frequency')
plt.xlabel('Time Interval (seconds)')
plt.show()